# generated by datamodel-codegen:
#   filename:  https://csrc.nist.gov/schema/nvd/api/2.0/cpe_api_json_2.0.schema
#   timestamp: 2023-03-02T10:17:39+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional
from uuid import UUID

from pydantic import BaseModel, Extra, Field, constr


class DefTitle(BaseModel):
    """
    Human readable title for CPE
    """

    class Config:
        extra = Extra.forbid

    title: str
    lang: str


class Type(Enum):
    Advisory = 'Advisory'
    Change_Log = 'Change Log'
    Product = 'Product'
    Project = 'Project'
    Vendor = 'Vendor'
    Version = 'Version'


class DefReference(BaseModel):
    """
    Internet resource for CPE
    """

    class Config:
        extra = Extra.forbid

    ref: constr(
        regex=r'^([A-Za-z][A-Za-z0-9+.-]+):(\/\/([^@]+@)?([A-Za-z0-9.\-_~]+)(:\d+)?)?((?:[A-Za-z0-9-._~]|%[A-Fa-f0-9]|[!$&\'\[\]()*+,;=:@])+(?:\/(?:[A-Za-z0-9-._~]|%[A-Fa-f0-9]|[!$&\'\[\]()*+,;=:@])*)*|(?:\/(?:[A-Za-z0-9-._~]|%[A-Fa-f0-9]|[!$&\'()*+,;=:@])+)*)?(\?(?:[A-Za-z0-9-._~]|%[A-Fa-f0-9]|[!$&\'\[\]()*+,;=:@]|[/?])*)?(\#(?:[A-Za-z0-9-._~]|%[A-Fa-f0-9]|[!$&\'\[\]()*+,;=:@]|[/?])*)?$'
    )
    type: Optional[Type] = None


class DeprecatedByItem(BaseModel):
    cpeName: Optional[str] = None
    cpeNameId: Optional[UUID] = None


class Deprecate(BaseModel):
    cpeName: Optional[str] = None
    cpeNameId: Optional[UUID] = None


class CpeItem(BaseModel):
    class Config:
        extra = Extra.forbid

    deprecated: bool
    cpeName: str
    cpeNameId: UUID
    created: datetime
    lastModified: datetime
    titles: Optional[List[DefTitle]] = None
    refs: Optional[List[DefReference]] = None
    deprecatedBy: Optional[List[DeprecatedByItem]] = None
    deprecates: Optional[List[Deprecate]] = None


class DefCpe(BaseModel):
    class Config:
        extra = Extra.forbid

    cpe: CpeItem


class CpeModel(BaseModel):
    class Config:
        extra = Extra.forbid

    resultsPerPage: int
    startIndex: int
    totalResults: int
    format: str
    version: str
    timestamp: datetime
    products: List[DefCpe] = Field(..., description='NVD feed array of CPE')
