"""add vuln_cert table

Revision ID: 03f01bf9a755
Revises: d4df74b54307
Create Date: 2023-01-26 15:43:27.914229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f01bf9a755'
down_revision = 'd4df74b54307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vuln_cpes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vuln_id', sa.String(length=20), nullable=True),
    sa.Column('cpe', sa.String(length=256), nullable=True),
    sa.Column('sys_creation_date', sa.DateTime(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('cond', sa.String(length=10), nullable=False, comment='The condition between the records of the same group AND/OR'),
    sa.Column('negate', sa.Boolean(), nullable=True, comment='Indicate if the condition result is to be negated'),
    sa.Column('vulnerable', sa.Boolean(), nullable=True, comment='Indicate if the specified CPE is vulnerable'),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('parent_group_id', sa.Integer(), nullable=False),
    sa.Column('part', sa.String(length=1), nullable=True, comment='the part of CPE'),
    sa.Column('vendor', sa.String(length=128), nullable=True, comment='the vendor of CPE'),
    sa.Column('product', sa.String(length=128), nullable=True, comment='the product of CPE'),
    sa.Column('version', sa.String(length=128), nullable=True, comment='the version of CPE'),
    sa.Column('version_lt', sa.String(length=128), nullable=True, comment='the little version of CPE'),
    sa.Column('version_le', sa.String(length=128), nullable=True, comment='the little or equal version of CPE'),
    sa.Column('version_gt', sa.String(length=128), nullable=True, comment='the greater version of CPE'),
    sa.Column('version_ge', sa.String(length=128), nullable=True, comment='the greater or equal version of CPE'),
    sa.Column('update', sa.String(length=128), nullable=True, comment='the update of CPE'),
    sa.Column('edition', sa.String(length=128), nullable=True, comment='the edition of CPE'),
    sa.Column('language', sa.String(length=128), nullable=True, comment='the language of CPE'),
    sa.Column('sw_edition', sa.String(length=128), nullable=True, comment='the sw_edition of CPE'),
    sa.Column('target_sw', sa.String(length=128), nullable=True, comment='the target_sw of CPE'),
    sa.Column('target_hw', sa.String(length=128), nullable=True, comment='the target_hw of CPE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Table that contains the list of Vulnerabilities'
    )
    op.create_index(op.f('ix_vuln_cpes_vuln_id'), 'vuln_cpes', ['vuln_id'], unique=False)
    op.create_index('vuln_cpe_idx1', 'vuln_cpes', ['product', 'version', 'vendor'], unique=False)
    op.create_unique_constraint('vuln_uix_1', 'vuln', ['vuln_id'])
    op.create_table_comment(
        'vuln',
        'Table that contains the list of Vulnerabilities',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'vuln',
        existing_comment='Table that contains the list of Vulnerabilities',
        schema=None
    )
    op.drop_constraint('vuln_uix_1', 'vuln', type_='unique')
    op.drop_index('vuln_cpe_idx1', table_name='vuln_cpes')
    op.drop_index(op.f('ix_vuln_cpes_vuln_id'), table_name='vuln_cpes')
    op.drop_table('vuln_cpes')
    # ### end Alembic commands ###
