"""add custom function

Revision ID: 892034da2349
Revises: 03f01bf9a755 
Create Date: 2023-01-29 15:43:27.914229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892034da2349'
down_revision = '03f01bf9a755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    CREATE OR REPLACE FUNCTION ver_pad(text, integer) 
    RETURNS text
    AS $$
    DECLARE
        input_string text := $1;
        max_length integer := $2;
        output_string text;
        parts text[];
        i integer;
    BEGIN
        parts := string_to_array(input_string, '.');
        output_string := '';
        FOR i in 1..array_length(parts, 1) 
        LOOP
        output_string := output_string || lpad(parts[i], max_length, '0') || '.';
        END LOOP;
        output_string := substring(output_string, 1, length(output_string) - 1);
        RETURN output_string;
    END;
    $$ LANGUAGE plpgsql; 
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP FUNCTION ver_ad(text, integer);")
    # ### end Alembic commands ###
