"""Add EPSS table

Revision ID: 9a14a98e9e6d
Revises: 2f14a6a5afe8
Create Date: 2024-03-12 13:30:54.706771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a14a98e9e6d'
down_revision = '2f14a6a5afe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=20), nullable=True, comment='The ID of the CVE'),
    sa.Column('epss_score', sa.Float(), nullable=False, comment='the score of the epss'),
    sa.Column('percentile', sa.Float(), nullable=False, comment='the percentile of the epss'),
    sa.Column('date', sa.DateTime(), nullable=False, comment='Date when the EPSS record has been downloaed'),
    sa.Column('changed', sa.Boolean(), nullable=True, comment='indicate if epss_score has been changed'),
    sa.PrimaryKeyConstraint('id'),
    comment='Table that contains the list of EPSS'
    )
    op.create_index('epss_idx1', 'epss', ['cve_id'], unique=False)
    op.create_index(op.f('ix_epss_cve_id'), 'epss', ['cve_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_epss_cve_id'), table_name='epss')
    op.drop_index('epss_idx1', table_name='epss')
    op.drop_table('epss')
    # ### end Alembic commands ###

