"""CWE table

Revision ID: c1f79cef457f
Revises: 892034da2349
Create Date: 2023-02-03 14:29:29.393104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1f79cef457f'
down_revision = '892034da2349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cwe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cwe_id', sa.Integer(), nullable=False, comment='The ID of the CWE'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='the name of the CWE'),
    sa.Column('status', sa.String(length=128), nullable=True, comment='the status of the CWE'),
    sa.Column('description', sa.Text(), nullable=True, comment='the description of the CWE'),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='CPE JSON representation'),
    sa.PrimaryKeyConstraint('id'),
    comment='Table that contains the list of CWEs'
    )
    #op.create_index('cwe_idx1', 'cwe', ['name'], unique=False)
    op.execute('CREATE INDEX cwe_idx1 on cwe (name varchar_pattern_ops)')
    op.execute('CREATE INDEX cwe_idx2 ON cwe (description text_pattern_ops);')
    op.create_index(op.f('ix_cwe_cwe_id'), 'cwe', ['cwe_id'], unique=False)
    op.execute('CREATE INDEX cpe_idx2 ON cpe (title_en text_pattern_ops);')
    op.add_column('vuln', sa.Column('description', sa.Text(), nullable=True, comment='the description of the CVE'))
    op.execute('CREATE INDEX vuln_idx1 ON vuln (description text_pattern_ops);')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('vuln_idx1', table_name='vuln')
    op.drop_column('vuln', 'description')
    op.drop_index('cpe_idx2', table_name='cpe')
    op.drop_index(op.f('ix_cwe_cwe_id'), table_name='cwe')
    op.drop_index('cwe_idx2', table_name='cwe')
    op.drop_index('cwe_idx1', table_name='cwe')
    op.drop_table('cwe')
    # ### end Alembic commands ###
