"""Change vuln description index type

Revision ID: ecd29e77afe3
Revises: 9a14a98e9e6d
Create Date: 2024-04-29 10:10:39.660073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd29e77afe3'
down_revision = '9a14a98e9e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('vuln_idx1', table_name='vuln')
    op.execute('CREATE INDEX vuln_idx1 ON vuln USING GIST (to_tsvector(\'english\', description));')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('vuln_idx1', table_name='vuln')
    op.execute('CREATE INDEX vuln_idx1 ON vuln (description text_pattern_ops);')
    # ### end Alembic commands ###
